name: Deploy to server 

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest

        env:
            Name : Sergio
        steps:
            - name: hola gente 
              run: echo "Hola $Name"

    
    second_job :

        if: ${{ github.ref == 'refs/heads/main'}}
        needs: first_job
        runs-on: ubuntu-latest

        steps:
            - name: hola gente 
              run: echo "Hola sergio"
    
