name: Deploy to server 

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest

        steps:
            - name: hola gente 
              run: echo "Hola sergio"

    
    second_job :

        if: ${{ github.ref == 'refs/heads/main'}}
        needs: first_job
        runs-on: ubuntu-latest

        steps:
            - name: hola gente 
              run: echo "Hola sergio"
    
    third_job:
        needs : first_job
        if: ${{ github.ref == 'refs/heads/main'}}
        runs-on: ubuntu-latest

        steps:
            - name : usando contextos 
              run: echo "Hola aprendi a usar github actions"
