name: Deploy to server 

on: push

jobs:
    first_jobs:
        runs-on: ubuntu-latest

        steps:
            - name: hola gente 
              run: echo "Hola sergio"

    
    second_job :

        if: ${{ github.ref == 'refs/heads/main'}}
        needs: first_jobs
        runs-on: ubuntu-latest

        steps:
            - name: hola gente 
              run: echo "Hola sergio"
