name: Deploy to server 

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest

        outputs:
            salida : ${{ steps.step_1.outputs.my_variable }}

        env:
            Name : Sergio
 

        steps:
            - name: working dir
              id: step_1
              run: echo "my_variable=Hola mundo" >>  $GITHUB_OUTPUT

            - name: print variable
              run: echo "${{ steps.step_1.outputs.my_variable }}"

  
    second_job :

        needs: first_job
        runs-on: ubuntu-latest

        env:
            Salida : ${{ needs.first_job.outputs.salida }}

        steps:
            - name: hola gente 
              run: echo "$Salida"
    
