name: Deploy to server 

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest

        outputs:
            salida : 

        env:
            Name : Sergio
 

        steps:
            - name: Generar archivo
              run: |
                 echo "archivo prueba" >> test.log

            - name : Subir artefacto
              uses: actions/upload-artifact@v4
              with: 
                name: archivo-test
                path: test.log
