name: Deploy to server 

on: push

jobs:
    first_jobs:
        runs-on: ubuntu-latest

        steps:
            - name: hola gente 
              run: cat hola.txt

    
    second_job:
        if : false 
        needs: first_jobs
        runs-on: ubuntu-latest

        steps:
            - name: hola gente 
              run: echo "Hola sergio"