name: Deploy to server 

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                massage: ["hola", "mundo", "sergi"]

        steps:
            - name: Imprimir mensaje
              run: echo "${{ matrix.massage }}"

    
            
